create table if not exists messages
(
    id      bigint generated by default as identity,
    message varchar(255),
    chat_id bigint,
    user_id bigint,
    primary key (id)
);

alter table if exists messages
    add constraint FK64w44ngcpqp99ptcb9werdfmb
        foreign key (chat_id)
            references chats;

alter table if exists messages
    add constraint FKpsmh6clh3csorw43eaodlqvkn
        foreign key (user_id)
            references users